docs_dir: documentation
theme: readthedocs
theme_dir: .theme

site_name: LIBXSMM
site_author: Hans Pabst
copyright:  <a href="LICENSE">BSD 3-Clause License</a>
site_description: Library targeting Intel Architecture for small, dense or sparse matrix multiplications, and small convolutions.
repo_url: https://github.com/hfp/libxsmm.git

pages:
- index.md
- Domains:
  - "MM: Matrix Multiplication": libxsmm_mm.md
  - "DNN: Deep Neural Networks": libxsmm_dnn.md
  - "AUX: Service Functions": libxsmm_aux.md
  - "PROF: Perf. Profiling": libxsmm_prof.md
  - "TUNE: Customization": libxsmm_tune.md
  - "BE: Backend": libxsmm_be.md
- Applications:
  - CP2K: cp2k.md
  - TensorFlow: tensorflow.md
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
